[package]
name = "denk_algo"
version = "0.1.0"
edition = "2021"

[dependencies]

inquire = "0.6.2"
colored = "2.0.0"
clearscreen = "2.0.1"
crossterm = "0.19"
rand = "0.8"
rand_chacha = "0.3"
rayon = "1.7"