[package]
name = "denk_algo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.6.2"
colored = "2.0.0"
fastrand = "1.9.0"

clearscreen = "2.0.1"
crossterm = "0.19"

rayon = "1.7"